resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

      threadServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 60
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true

      roomServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 8
        failureRateThreshold: 55
        waitDurationInOpenState: 12s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
