logging:
  level:
    org.springframework.cloud.gateway.handler.FilteringWebHandler: DEBUG
    org.springframework.cloud.gateway.filter.factory: DEBUG
    io.github.resilience4j: DEBUG

resilience4j:
  circuitbreaker:
    instances:
      userServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true

      threadServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true

      roomServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 8
        failureRateThreshold: 50
        waitDurationInOpenState: 12s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 1
        automaticTransitionFromOpenToHalfOpenEnabled: true
