server:
  port: 8080

spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8000/realms/threadstacksuser
          jwk-set-uri: http://localhost:8000/realms/threadstacksuser/protocol/openid-connect/certs
